traefik:
  enabled: true
  namespace: rocket
  replicas: 1  # Default to 1 for Raspberry Pi
  
  # Service configuration
  service:
    type: LoadBalancer  # Use LoadBalancer for external access
    port: 80
    annotations: 
      # Add annotations if needed for your specific environment
      metallb.universe.tf/allow-shared-ip: "true"
  
  # SSL configuration
  ssl:
    enabled: true
    redirect: true
    email: "admin@example.com"  # Replace with actual email for Let's Encrypt
  
  # Dashboard configuration
  dashboard:
    enabled: true
    secure: false  # Set to false to allow direct access for troubleshooting
    # For production, set to true and create proper ingress
  
  # Resource limits - optimized for Raspberry Pi
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  # Affinity and anti-affinity rules
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - traefik
            topologyKey: kubernetes.io/hostname
  
  # Autoscaling configuration
  autoscaling: 
    enabled: false  # Disabled by default for Raspberry Pi
    minReplicas: 1
    maxReplicas: 2
    cpuTargetUtilization: 80
    memoryTargetUtilization: 80
  
  # Tolerations - useful for dedicated nodes
  tolerations: []
  
  # Node selector - useful for ARM architecture
  nodeSelector: 
    kubernetes.io/arch: arm64  # For Raspberry Pi 4
  
  # Persistent storage for Let's Encrypt certificates
  persistence:
    enabled: false  # Disable for now to get basic functionality working
    size: 128Mi
    storageClass: ""  # Use default storageClass
  
  # Additional configuration
  additionalArguments:
    - "--log.level=INFO"
    - "--api.insecure=true"  # Only for development
    - "--metrics.prometheus=true"
    - "--providers.kubernetesingress.ingressclass=traefik"
    - "--entrypoints.websecure.http.tls=true"