{{- if .Values.mongodb.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb-auth
  labels:
    app: {{ .Release.Name }}-mongodb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.mongodb.auth.rootPassword }}
  mongodb-root-password: {{ .Values.mongodb.auth.rootPassword | b64enc | quote }}
  {{- else }}
  mongodb-root-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.auth.password }}
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc | quote }}
  {{- else }}
  mongodb-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  mongodb-username: {{ .Values.mongodb.auth.username | b64enc | quote }}
  mongodb-database: {{ .Values.mongodb.auth.database | b64enc | quote }}
{{- end }}