apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: {{ .Values.traefik.namespace }}
  labels:
    app: traefik
data:
  traefik.toml: |
    [global]
      checkNewVersion = false
      sendAnonymousUsage = false

    [log]
      level = "INFO"

    [entryPoints]
      [entryPoints.web]
        address = ":80"
        {{- if and .Values.traefik.ssl.enabled .Values.traefik.ssl.redirect }}
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"
        {{- end }}

      [entryPoints.websecure]
        address = ":443"
        {{- if .Values.traefik.ssl.enabled }}
        [entryPoints.websecure.http.tls]
          certResolver = "default"
        {{- end }}

      [entryPoints.metrics]
        address = ":8082"

      [entryPoints.dashboard]
        address = ":9000"

    [api]
      dashboard = true
      insecure = {{ not .Values.traefik.dashboard.secure }}
      # Dashboard access is available at /dashboard/ with trailing slash

    [metrics]
      [metrics.prometheus]
        entryPoint = "metrics"

    [providers]
      [providers.kubernetesIngress]
        ingressClass = "traefik"
      [providers.kubernetesCRD]
        # Use both old and new API groups for compatibility
        # in order to support all Traefik CRD versions
        allowCrossNamespace = true 
        allowExternalNameServices = true
        
    {{- if and .Values.traefik.ssl.enabled .Values.traefik.persistence.enabled }}
    [certificatesResolvers.default.acme]
      email = "admin@example.com"
      storage = "/data/acme.json"
      [certificatesResolvers.default.acme.tlsChallenge]
    {{- end }}

    [accessLog]
      format = "json"
      
    # Enable native Traefik CRDs
    [experimental]
      kubernetesGateway = true
