apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  namespace: {{ .Values.traefik.namespace }}
  labels:
    app: traefik
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.traefik.replicas }}
  selector:
    matchLabels:
      app: traefik
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
    spec:
      serviceAccountName: traefik-ingress-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
      {{- with .Values.traefik.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.traefik.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.traefik.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: traefik
        image: traefik:{{ .Chart.AppVersion }}
        args:
        - --configfile=/config/traefik.toml
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        ports:
        - name: web
          containerPort: 80
        - name: websecure
          containerPort: 443
        - name: dashboard
          containerPort: 9000
        - name: metrics
          containerPort: 8082
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          {{- toYaml .Values.traefik.resources | nindent 10 }}
        volumeMounts:
        - name: traefik-config
          mountPath: /config
        {{- if .Values.traefik.persistence.enabled }}
        - name: data
          mountPath: /data
        {{- end }}
      volumes:
      - name: traefik-config
        configMap:
          name: traefik-config
      {{- if .Values.traefik.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: traefik-acme
      {{- end }}