{{- if .Values.traefik.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: traefik-ingress-controller
  namespace: {{ .Values.traefik.namespace }}
  labels:
    app: traefik
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: traefik-ingress-controller
  minReplicas: {{ .Values.traefik.replicas }}
  maxReplicas: {{ .Values.traefik.autoscaling.maxReplicas | default 5 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.traefik.autoscaling.cpuTargetUtilization | default 80 }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.traefik.autoscaling.memoryTargetUtilization | default 80 }}
{{- end }}