apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: {{ .Values.traefik.namespace }}
  labels:
    app: traefik
  {{- with .Values.traefik.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.traefik.service.type }}
  externalTrafficPolicy: Local
  ports:
  - port: {{ .Values.traefik.service.port }}
    name: web
    targetPort: web
    protocol: TCP
  - port: 443
    name: websecure
    targetPort: websecure
    protocol: TCP
  {{- if .Values.traefik.dashboard.enabled }}
  - port: 9000
    name: dashboard
    targetPort: dashboard
    protocol: TCP
  {{- end }}
  - port: 8082
    name: metrics
    targetPort: metrics
    protocol: TCP
  selector:
    app: traefik